import { blogPosts } from '@/lib/blog-posts'
import BlogCard from './BlogCard'

export const metadata = {
  title: 'Insulation Blog | Evrnew LLC — Seattle & Western WA',
  description: 'Expert insulation guides, tips, and local rebate information for homeowners across King, Snohomish, and Skagit counties in Washington State.',
}

export default function BlogPage() {
  return (
    <div style={{ maxWidth: 860, margin: '0 auto', padding: '32px 24px' }}>
      {/* Header */}
      <div style={{ marginBottom: 40 }}>
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 6,
          background: '#f0f9ff',
          border: '1px solid #bae6fd',
          color: '#0284c7',
          fontSize: 10,
          padding: '3px 10px',
          borderRadius: 999,
          letterSpacing: '0.08em',
          marginBottom: 12,
          fontWeight: 600
        }}>
          SEO CONTENT
        </div>
        <h1 style={{
          fontSize: 28,
          fontWeight: 700,
          color: '#0f172a',
          margin: '0 0 8px',
          letterSpacing: '-0.02em'
        }}>
          Insulation Resources for Western WA Homeowners
        </h1>
        <p style={{ color: '#64748b', fontSize: 14, margin: 0, lineHeight: 1.6 }}>
          Expert guides on insulation types, crawl space encapsulation, energy rebates, and home comfort written for King, Snohomish, and Skagit County homeowners.
        </p>
      </div>

      {/* Post Grid */}
      <div style={{ display: 'grid', gap: 20 }}>
        {blogPosts.map((post) => (
          <BlogCard key={post.slug} post={post} />
        ))}
      </div>

      {/* Footer note */}
      <div style={{
        marginTop: 40,
        padding: '16px 20px',
        background: '#fafafa',
        border: '1px solid #e2e8f0',
        borderRadius: 8,
        display: 'flex',
        alignItems: 'center',
        gap: 10
      }}>
        <span style={{ fontSize: 16 }}>🤖</span>
        <div>
          <p style={{ margin: 0, fontSize: 11, color: '#64748b', lineHeight: 1.5 }}>
            <strong style={{ color: '#334155' }}>Auto-generated by Erel SEO Agent</strong> — new posts publish every Monday and Thursday targeting geo-specific insulation keywords across all 20+ service area cities.
          </p>
        </div>
      </div>
    </div>
  )
}
